
// This file has been generated by the GUI designer. Do not modify.
namespace Psiga
{
	public partial class TextureWidget
	{
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Psiga.PannableDrawingArea pannabledrawingarea1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button exportPNG;
		
		private global::Gtk.Button resetTransforms;
		
		private global::Gtk.CheckButton showAtlasLabels;
		
		private global::Gtk.CheckButton showAtlasBoxes;
		
		private global::Gtk.CheckButton blackBackground;
		
		private global::Gtk.Label previewPage;
		
		private global::Psiga.PropertyView propertyview;
		
		private global::Gtk.Label propertiesPage;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Psiga.TextureWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Psiga.TextureWidget";
			// Container child Psiga.TextureWidget.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.pannabledrawingarea1 = new global::Psiga.PannableDrawingArea ();
			this.pannabledrawingarea1.Name = "pannabledrawingarea1";
			this.vbox1.Add (this.pannabledrawingarea1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.pannabledrawingarea1]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.exportPNG = new global::Gtk.Button ();
			this.exportPNG.CanFocus = true;
			this.exportPNG.Name = "exportPNG";
			this.exportPNG.UseUnderline = true;
			this.exportPNG.Label = global::Mono.Unix.Catalog.GetString ("Export as PNG");
			this.hbox1.Add (this.exportPNG);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.exportPNG]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.resetTransforms = new global::Gtk.Button ();
			this.resetTransforms.CanFocus = true;
			this.resetTransforms.Name = "resetTransforms";
			this.resetTransforms.UseUnderline = true;
			this.resetTransforms.Label = global::Mono.Unix.Catalog.GetString ("Reset Transforms");
			this.hbox1.Add (this.resetTransforms);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.resetTransforms]));
			w3.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.showAtlasLabels = new global::Gtk.CheckButton ();
			this.showAtlasLabels.CanFocus = true;
			this.showAtlasLabels.Name = "showAtlasLabels";
			this.showAtlasLabels.Label = global::Mono.Unix.Catalog.GetString ("Show Atlas Labels");
			this.showAtlasLabels.DrawIndicator = true;
			this.showAtlasLabels.UseUnderline = true;
			this.vbox1.Add (this.showAtlasLabels);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.showAtlasLabels]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.showAtlasBoxes = new global::Gtk.CheckButton ();
			this.showAtlasBoxes.CanFocus = true;
			this.showAtlasBoxes.Name = "showAtlasBoxes";
			this.showAtlasBoxes.Label = global::Mono.Unix.Catalog.GetString ("Show Atlas Boxes");
			this.showAtlasBoxes.DrawIndicator = true;
			this.showAtlasBoxes.UseUnderline = true;
			this.vbox1.Add (this.showAtlasBoxes);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.showAtlasBoxes]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.blackBackground = new global::Gtk.CheckButton ();
			this.blackBackground.CanFocus = true;
			this.blackBackground.Name = "blackBackground";
			this.blackBackground.Label = global::Mono.Unix.Catalog.GetString ("Black Background");
			this.blackBackground.DrawIndicator = true;
			this.blackBackground.UseUnderline = true;
			this.vbox1.Add (this.blackBackground);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.blackBackground]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			this.notebook1.Add (this.vbox1);
			// Notebook tab
			this.previewPage = new global::Gtk.Label ();
			this.previewPage.Name = "previewPage";
			this.previewPage.LabelProp = global::Mono.Unix.Catalog.GetString ("Preview");
			this.notebook1.SetTabLabel (this.vbox1, this.previewPage);
			this.previewPage.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.propertyview = new global::Psiga.PropertyView ();
			this.propertyview.Events = ((global::Gdk.EventMask)(256));
			this.propertyview.Name = "propertyview";
			this.notebook1.Add (this.propertyview);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.propertyview]));
			w9.Position = 1;
			// Notebook tab
			this.propertiesPage = new global::Gtk.Label ();
			this.propertiesPage.Name = "propertiesPage";
			this.propertiesPage.LabelProp = global::Mono.Unix.Catalog.GetString ("Properties");
			this.notebook1.SetTabLabel (this.propertyview, this.propertiesPage);
			this.propertiesPage.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.exportPNG.Clicked += new global::System.EventHandler (this.onExportPNG);
			this.resetTransforms.Clicked += new global::System.EventHandler (this.onResetTransforms);
			this.showAtlasLabels.Toggled += new global::System.EventHandler (this.showAtlasLabelsToggled);
			this.showAtlasBoxes.Toggled += new global::System.EventHandler (this.showAtlasBoxesToggled);
			this.blackBackground.Toggled += new global::System.EventHandler (this.toggleBlackBackground);
		}
	}
}
